### PR TITLE
Cleanup emit temp register output + misc fixes

### LINKED ISSUE #16: Implement Const/Copy cleanup after MIR lowering
Currently the translation from the AST representation to the compiler MIR representation is pretty direct and leaves redundant constant and copy assignments. This is inefficient and makes it harder to understand the MIR code. 

A simple block level copy/const propagation pass would help this out a lot.

### PR DESCRIPTION
**Pull request by mrkmarron**
Fixes #16 

Changes:
Tidy up temp register emit and IR output.

### CODE REVIEW

File: ref_impl/src/compiler/mir_emitter.ts [hunk 1]
```diff
@@ -360,7 +361,18 @@ class MIRBodyEmitter {
...
+        let ibody = new MIRBody(file, sinfo, this.m_varNames, this.m_blockMap);
+
+        //console.log("Original Body ----");
+        //console.log(ibody.jsonify());
+
+        propagateTmpAssignForBody(ibody);
+        removeDeadTempAssignsFromBody(ibody);
+
+        //console.log("Cleaned Body ----");
+        //console.log(ibody.jsonify());
```
Comment (catchmareck) [inline ref_impl/src/compiler/mir_emitter.ts]: Are those comments necessary?

**Comment by mrkmarron** [comment]
Thanks for the review comments -- updated to address them.
